#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <raylib.h>

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define SCREEN_CENTER_X (SCREEN_WIDTH / 2.0f)
#define SCREEN_CENTER_Y (SCREEN_HEIGHT / 2.0f)

#define SHIP_MAX_SPEED 200.0f
#define SHIP_ROTATION_SPEED 150.0f
#define SHIP_ACCELERATION 200.0f
#define SHIP_DECELERATION 50.0f

#define LASER_SPEED 300.0f
#define LASER_MAX_DISTANCE 600.0f
#define MAX_LASERS 50

#define MAX_LARGE_ASTEROIDS 4
#define MAX_MEDIUM_ASTEROIDS 8
#define MAX_SMALL_ASTEROIDS 16
#define ASTEROID_MIN_SPEED 50.0f
#define ASTEROID_MAX_SPEED 250.0f

#endif